name: Edit issue on Jira

on:
    issue_comment:
        types: [created]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Jira Login
            id: login
            uses: atlassian/gajira-login@v2.0.0
            env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          - name: Extract JIRA number
            id: extract_jira_number
            run: echo "::set-output name=jira_number::$(echo ${{ github.event.issue.title }}| sed 's/.*\[\(${{ secrets.JIRA_PROJECT }}-[[:digit:]]\{1,\}\)\].*/\1/')"          
          
          - name: Jira Add comment on issue
            id: add_comment_jira_issue
            uses: atlassian/gajira-comment@v2.0.0
            with:
              issue: ${{ steps.extract_jira_number.outputs.jira_number }}
              comment: |
                  Gitlab username : ${{ github.event.comment.user.login }}
                  Comment : 
                  ${{ github.event.comment.body }}
                  ----
                  {panel}
                  _See this comment in Github : ${{ github.event.comment.html_url }}_
                  {panel}
          
          - name: FAILED
            run: exit 1         