name: Create issue on Jira

on:
    issues:
        types: [opened]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"
          - name: Jira Login
            id: login
            uses: atlassian/gajira-login@v2.0.0
            env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          - name: Jira Create issue
            id: create_jira_issue
            uses: atlassian/gajira-create@v2.0.0
            with:
                project: GHTEST
                issuetype: Story
                summary: ${{ github.event.issue.title }}
                description: ${{ github.event.issue.body }}
          - name: Dump JIRA_RETURN
            env:
              JIRA_RETURN: ${{ toJson(steps.create_jira_issue.outputs) }}
            run: echo "$JIRA_RETURN"
 
          - name: Dump Title 2
            env: 
              ISSUE_TITLE: ${{ github.event.issue.title}}
            run: echo "$ISSUE_TITLE"                

          - name: Add comment after sync
            uses: actions/github-script@0.8.0
            with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '${{ steps.create_jira_issue.outputs.issue }}'
                })
          
          - name: Change Title
            uses: actions/github-script@0.8.0
            env: 
              ISSUE_TITLE: ${{ github.event.issue.title}}
            with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                github.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: '[${{ steps.create_jira_issue.outputs.issue }}]${{ env.ISSUE_TITLE }}'
                })