name: Create issue on Jira

on:
    issues:
        types: [opened]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Jira Login
            id: login
            uses: atlassian/gajira-login@v2.0.0
            env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          - name: Jira Create issue
            id: create_jira_issue
            uses: atlassian/gajira-create@v2.0.0
            with:
                project: GHTEST
                issuetype: Story
                summary: ${{ github.event.issue.title }}
                description: ${{ github.event.issue.body }}
          - name: Dump JIRA_RETURN
            env:
              JIRA_RETURN: ${{ toJson(steps.create_jira_issue.outputs) }}
            run: echo "$JIRA_RETURN"