name: Edit issue on Jira

on:
    issues:
        types: [edited]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Jira Login
            id: login
            uses: atlassian/gajira-login@v2.0.0
            env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          - name: Extract JIRA number
            id: extract_jira_number
            run: echo "::set-output name=jira_number::$(echo ${{ github.event.issue.title }}| sed 's/.*\[\(${{ secrets.JIRA_PROJECT }}-[[:digit:]]\{1,\}\)\].*/\1/')"          
          
          - name: Setup
            uses: atlassian/gajira-cli@master
            with:
              version: 1.0.20
          - name: Jira Edit issue
            id: edit_jira_issue
            run: jira edit --issue=${{ steps.extract_jira_number.outputs.jira_number }} --description="${{ github.event.issue.body }}\n----\n{panel}\n_[Github permalink |${{ github.event.issue.html_url }}]_\n{panel}"
