name: Set issue In Progress on Jira

on:
    push:
      
    pull_request:
      types: [opened, edited]
    issues:
      types: [edited]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          
          - name: Failed
            run: "exit 1"     